name: Terraform CI

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./assignment

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./assignment

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./assignment

      # Uncomment below to enable auto-apply (not recommended for production)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./assignment
