name: Terraform CI

env:
  aws-access-key-id: ${{ secrets.ACCESSKEY }}
  aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Uncomment below to enable auto-apply (not recommended for production)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
